import logging
from datetime import datetime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, ForeignKey, Table, DateTime
from sqlalchemy.orm import relationship
#logging.basicConfig()
#logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

Base = declarative_base()

user_project_role_table = Table(
    "user_project_role",
    Base.metadata,
    Column("user_id", Integer, ForeignKey("user.id")),
    Column("role_id", Integer, ForeignKey("role.id")),
    Column("project_id", Integer, ForeignKey("project.id")),
)

user_team_role_table = Table(
    "user_team_role",
    Base.metadata,
    Column("user_id", Integer, ForeignKey("user.id")),
    Column("role_id", Integer, ForeignKey("role.id")),
    Column("team_id", Integer, ForeignKey("team.id")),
)

class Entity(Base):
    """
        id: Entity id, numeric, unique for a given entity type, and autogenerated.
            Note that IDs are populated once session.flush() is performed.
    """
    __abstract__ = True

    id = Column(Integer, primary_key=True)

    def __init__(self, **kwargs):
        for k,v in kwargs.items():
            setattr(self, k, v)

    def __eq__(self, other):
        return other is not None and self.__class__ == other.__class__ and self.id == other.id

    def __hash__(self):
        return hash(f"{self.__class__.__name__}{self.id}")


class UserEntity(Entity):
    __tablename__ = "user"
    __mapper_args__ = {"concrete": True}

    user_name = Column(String(255))
    given_name = Column(String(50))
    family_name = Column(String(50))
    created_at = Column(DateTime, default=datetime.now())

    teams = relationship("TeamEntity", secondary=user_team_role_table, lazy="joined")
    projects = relationship("ProjectEntity", secondary=user_project_role_table, lazy="joined")

class TeamEntity(Entity):
    __tablename__ = "team"
    __mapper_args__ = {"concrete": True}

    name = Column(String(50))
    creator_id = Column(Integer, ForeignKey("user.id") )
    created_at = Column(DateTime, default=datetime.now())

    users = relationship("UserEntity", secondary=user_team_role_table, lazy="joined")
    projects = relationship("ProjectEntity", lazy="joined")

class RoleEntity(Entity):
    __tablename__ = "role"
    __mapper_args__ = {"concrete": True}

    name = Column(String(20))

class ProjectEntity(Entity):
    __tablename__ = "project"
    __mapper_args__ = {"concrete": True}

    name = Column(String(50))
    creator_id = Column(Integer, ForeignKey("user.id") )
    created_at = Column(DateTime, default=datetime.now())
    team_id = Column(Integer, ForeignKey("team.id"))

    team = relationship("TeamEntity")
    users = relationship("UserEntity", secondary=user_project_role_table, lazy="joined")



